name: get leaderboard from monkeytype

on:
  schedule:
    - cron: '10 0,1,2 * * *'
  workflow_dispatch:

jobs:
  get_leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: |
          npm install

      - name: Running script
        env:
          DB_URI: ${{ secrets.DB_URI }}
        run: |
          node index.js
